export { default as Logo } from "./logo.jpg"
export { default as WeatherBack } from "./weather_app_back.jpeg"
export { default as Like } from "./like.png"
export { default as Dislike } from "./dislike.png"
// export { default as Fon } from "./fon.jpg"
export { default as Fon } from "./fon_a.avif"